package com.yijing.divination.ui.theme

import androidx.compose.ui.graphics.Color

// 传统中国色
val ChineseRed = Color(0xFFDC143C)
val InkBlack = Color(0xFF2C3E50)
val PaperWhite = Color(0xFFFFFAF0)
val BambooGreen = Color(0xFF6B8E23)
val GoldYellow = Color(0xFFFFD700)

// Light Theme Colors
val md_theme_light_primary = Color(0xFF8B4513)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFFDDB3)
val md_theme_light_onPrimaryContainer = Color(0xFF2B1700)
val md_theme_light_secondary = Color(0xFF6B5D3F)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFF5E1BB)
val md_theme_light_onSecondaryContainer = Color(0xFF231B04)
val md_theme_light_tertiary = Color(0xFF4C6546)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFCEEBC3)
val md_theme_light_onTertiaryContainer = Color(0xFF092008)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF1F1B16)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF1F1B16)
val md_theme_light_surfaceVariant = Color(0xFFEDE1CF)
val md_theme_light_onSurfaceVariant = Color(0xFF4D4639)
val md_theme_light_outline = Color(0xFF7F7667)

// Dark Theme Colors
val md_theme_dark_primary = Color(0xFFFFB958)
val md_theme_dark_onPrimary = Color(0xFF4A2800)
val md_theme_dark_primaryContainer = Color(0xFF693C00)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFDDB3)
val md_theme_dark_secondary = Color(0xFFD8C5A1)
val md_theme_dark_onSecondary = Color(0xFF3A2F15)
val md_theme_dark_secondaryContainer = Color(0xFF52462A)
val md_theme_dark_onSecondaryContainer = Color(0xFFF5E1BB)
val md_theme_dark_tertiary = Color(0xFFB2CFA8)
val md_theme_dark_onTertiary = Color(0xFF1F361A)
val md_theme_dark_tertiaryContainer = Color(0xFF354D30)
val md_theme_dark_onTertiaryContainer = Color(0xFFCEEBC3)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1F1B16)
val md_theme_dark_onBackground = Color(0xFFEAE1D9)
val md_theme_dark_surface = Color(0xFF1F1B16)
val md_theme_dark_onSurface = Color(0xFFEAE1D9)
val md_theme_dark_surfaceVariant = Color(0xFF4D4639)
val md_theme_dark_onSurfaceVariant = Color(0xFFD0C5B4)
val md_theme_dark_outline = Color(0xFF998F80)
